/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jj */

#ifndef _Included_jj
#define _Included_jj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jj
 * Method:    greet
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jj_greet
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
